services:
  myapi:
    build: 
        context: .
        dockerfile: /Dockerfile.txt
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=12345*Onur
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"